development:
  adapter: sqlite3
  database: db/development.sqlite3
  encoding: unicode
  pool: 5
  username: henrikfogelberg
  password: password

test:
  adapter: sqlite3
  database: db/test.sqlite3
  encoding: unicode
  pool: 5
  username: henrikfogelberg
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: helenafogelberg
  pool: 5
  username: henrikfogelberg
  password: password
